version: "3.3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: